using System.Text;

namespace GcToolkit.SourceGenerators;

internal static class StringBuilderExtensions
{
    /// <summary>
    /// Emits a deterministic <c>&lt;auto-generated/&gt;</c> header. Unlike the WinUI Gallery
    /// reference (whose <c>AppendFullHeader</c> embeds <c>DateTime.Now</c>), this header carries
    /// no timestamp, so generated output is byte-identical for identical inputs — required for
    /// incremental-generator caching and reproducible builds (research R13).
    /// </summary>
    internal static StringBuilder AppendAutoGeneratedHeader(this StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// This file was produced by GcToolkit.SourceGenerators. Do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        return sb;
    }
}
